site_name: Zanata Server
docs_dir: docs
repo_name: GitHub
repo_url: http://www.github.com/zanata/zanata-server
theme: readthedocs
# theme_dir: For custom themes

pages:
- Home: 'index.md'
- Release notes: 'release-notes.md'
# Getting started
- Getting Started:
  - Translator Guide: 'user-guide/translator-guide.md'
  - Project Maintainer Guide: 'user-guide/project-maintainer-guide.md'
  - System admin guide: 'user-guide/system-admin/configuration/installation.md'
# Accounts
- Accounts:
  - Create new account: 'user-guide/account/account-sign-up.md'
  - Activate account: 'user-guide/account/account-activate.md'
  - Resend activation email: 'user-guide/account/account-resend-activation.md'
  - Account settings: 'user-guide/account/account-settings.md'
  - User profile: 'user-guide/account/user-profile.md'
  - User dashboard: 'user-guide/account/user-dashboard.md'
# Projects
- Projects:
  - Project view: 'user-guide/projects/project-view.md'
  - Creating a project: 'user-guide/projects/create-project.md'
  - Project team: 'user-guide/projects/project-team.md'
  - Project settings: 'user-guide/projects/project-settings.md'
  - Project types: 'user-guide/projects/project-types.md'
  - Validations: 'user-guide/projects/validations.md'
  - Import Projects: 'user-guide/projects/import-projects.md'
  - Gettext Project example: 'user-guide/projects/gettext-example.md'
  - Podir Project example: 'user-guide/projects/podir-example.md'
# Versions
- Versions:
  - Version view: 'user-guide/versions/version-view.md'
  - Creating a version: 'user-guide/versions/create-version.md'
  - Version settings: 'user-guide/versions/version-settings.md'
  - Join a group: 'user-guide/versions/request-to-join-group.md'
  - Merge translations: 'user-guide/versions/merge-translations.md'
# Documents
- Documents:
  - Upload documents: 'user-guide/documents/upload-documents.md'
  - Download translated documents: 'user-guide/documents/download-translated-documents.md'
  - Raw documents: 'user-guide/documents/raw-documents.md'
  - Custom document parameters: 'user-guide/documents/custom-document-param.md'
# Languages
- Languages:
  - Language team: 'user-guide/languages/language-team.md'
  - Add members: 'user-guide/languages/add-team-member.md'
  - Modify role: 'user-guide/languages/modify-role.md'
# Review
- Translation Review:
  - Overview: 'user-guide/review/overview.md'
  - Enabling review in version: 'user-guide/review/review-enable.md'
  - Add reviewer: 'user-guide/review/add-reviewer.md'
  - Start reviewing: 'user-guide/review/translation-review.md'
# Translation reuse
- Translation reuse:
   - Copy Trans: 'user-guide/translation-reuse/copy-trans.md'
   - Copy version: 'user-guide/translation-reuse/copy-version.md'
   - Merge translations: 'user-guide/translation-reuse/merge-trans.md'
   # TODO: TM Merge
# Groups
- Groups:
   - Group view: 'user-guide/groups/group-view.md'
   - Creating a group: 'user-guide/groups/create-group.md'
   - Group settings: 'user-guide/groups/group-settings.md'
# Editor
- Editor:
   - Overview: 'user-guide/editor/overview.md'
   - Editor view: 'user-guide/editor/editor-view.md'
   - Document view: 'user-guide/editor/documents-view.md'
   - Project search replace view: 'user-guide/editor/project-search-replace-view.md'
   - Keyboard shortcuts: 'user-guide/editor/keyboard-shortcuts.md'
   - Translation history: 'user-guide/editor/translation-history.md'
# Glossary
- Glossary:
  - Roles and Permissions: 'user-guide/glossary/glossary-roles-permissions.md'
  - Upload glossaries: 'user-guide/glossary/upload-glossaries.md'
  - Insert new term: 'user-guide/glossary/insert-term.md'
  - Edit glossaries: 'user-guide/glossary/edit-glossaries.md'
  - Delete glossaries: 'user-guide/glossary/delete-glossaries.md'
# API
- Zanata API: 'user-guide/api/api.md'
# Client
- Zanata client: 'user-guide/client/client.md'
# Drupal
- Drupal plugin: 'user-guide/drupal/drupal.md'
# Admin
- Admin:
  - Overview: 'user-guide/admin/admin-overview.md'
  - Contact Admin: 'user-guide/admin/contact-admin.md'
  - Server configuration: 'user-guide/admin/server-config.md'
  - Manage search: 'user-guide/admin/manage-search.md'
  - Process manager: 'user-guide/admin/process-manager.md'
  - Role assignment rules: 'user-guide/admin/role-assignment-rules.md'
  - Statistic: 'user-guide/admin/statistic.md'
  - Monitoring: 'user-guide/admin/monitoring.md'
  # TODO: tmx, Manage users, Manage roles
# System admin
- System Admin:
  - Installation: 'user-guide/system-admin/configuration/installation.md'
  - Authentication: 'user-guide/system-admin/configuration/authentication.md'
  - Document Storage Directory: 'user-guide/system-admin/configuration/document-storage-directory.md'
  - Email: 'user-guide/system-admin/configuration/email.md'
  - Caches: 'user-guide/system-admin/configuration/infinispan.md'
  - JMS Messaging: 'user-guide/system-admin/configuration/jms-messaging.md'
